package io.github.alextoday111.projectd.lexer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

final class ExampleLexerTest {
    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {"01_simple.d", "02_calculator.d", "03_nested_values.d",
            "01_calculator.d", "02_nested_collections.d", "03_bubble_sort.d", "04_higher_order.d"})
    void matchesReviewedTokenFixture(String fileName) throws IOException {
        String source = Files.readString(Path.of("examples", "valid", fileName), StandardCharsets.UTF_8);
        List<String> actual = new Lexer(source).scanTokens().stream()
                .map(ExampleLexerTest::describeToken).collect(Collectors.toList());

        // Static fixtures are committed expectations, never regenerated by Maven.
        try (InputStream stream = getClass().getResourceAsStream("/lexer-examples/" + fileName + ".tokens")) {
            assertNotNull(stream, "Missing expected token fixture for " + fileName);
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
                assertEquals(reader.lines().collect(Collectors.toList()), actual, fileName);
            }
        }
    }

    private static String describeToken(Token token) {
        Object value = token.getValue();
        String typedValue = value == null ? "-" : value.getClass().getSimpleName() + ":" + escape(value.toString());
        return token.getType() + "\t" + escape(token.getLexeme()) + "\t" + typedValue
                + "\t" + token.getLine() + ":" + token.getColumn();
    }

    private static String escape(String text) {
        return text.replace("\\", "\\\\").replace("\r", "\\r")
                .replace("\n", "\\n").replace("\t", "\\t");
    }
}
